spring:
  profiles: dev
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yingfu
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.liaojun.*.*.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.liaojun.component.mybatis.mapper.IBaseMapper
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


server:
  port: 81

logging:
    config: classpath:logback.xml
